language: node_js
node_js:
  - node

addons:
  chrome: stable

services:
  - xvfb

env:
  - BROWSER=ChromeCi

cache:
  yarn: true
  npm: true
  directories:
    - www/node_modules

before_install:
  - export DISPLAY=:99.0

install:
  - yarn bootstrap

after_script:
  - node_modules/.bin/codecov

branches:
  only:
    - master
    - next
    - /^v.*-dev$/
