name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        browser: [ChromeHeadless]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checking out Repository
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Chrome (macOS)
      if: matrix.os == 'macOS-latest'
      run: brew cask install google-chrome
    - name: Install Dependencies
      run: yarn bootstrap
    - name: Run Tests
      run: yarn test
      env:
        BROWSER: ${{ matrix.browser }}
    - name: Upload Test Coverage to codecov
      # Only upload it a single time
      if: matrix.os == 'ubuntu-latest'
      run: yarn run codecov
